//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalVersionControl {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SettingsStore : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsStore defaultInstance = ((SettingsStore)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsStore())));
        
        public static SettingsStore Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultLocation {
            get {
                return ((string)(this["DefaultLocation"]));
            }
            set {
                this["DefaultLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exe")]
        public string DefaultExclude {
            get {
                return ((string)(this["DefaultExclude"]));
            }
            set {
                this["DefaultExclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".LVCControlLog")]
        public string logFolderName {
            get {
                return ((string)(this["logFolderName"]));
            }
            set {
                this["logFolderName"] = value;
            }
        }
    }
}
